name: CI kmws-accounting

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci-kmws-accounting.yml
      - kmws-accounting/**

jobs:
  qa:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: kmws-accounting
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r ../requirements-dev.txt
          pip install .
      - name: Lint
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test
        run: |
          pytest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1

  publish:
    runs-on: ubuntu-latest
    # needs: qa
    steps:
      # - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - uses: aws-actions/amazon-ecr-login@v1
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.AWS_ECR_HOST }}/kmws-accounting:${{ github.sha }}
          context: ./kmws-accounting
          cache-from: type=gha
          cache-to: type=gha,mode=max
