name: CI kmws-ui

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci-kmws-ui.yml
      - kmws-ui/**

jobs:
  qa:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: kmws-ui
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: npm
          cache-dependency-path: kmws-ui/package-lock.json
      - name: Install
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint

  publish:
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - uses: aws-actions/amazon-ecr-login@v1
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.AWS_ECR_HOST }}/kmws-ui:${{ github.sha }}
          context: kmws-ui
          cache-from: type=gha
          cache-to: type=gha,mode=max
